import 'package:flutter_riverpod/flutter_riverpod.dart';

import '../../../core/providers/connectivity_providers.dart';
import '../../../core/services/sync_queue_service.dart';
import '../../elevator/models/elevator_model.dart';
import '../../elevator/providers/elevator_providers.dart';
import '../models/maintenance_log_model.dart';
import '../providers/maintenance_providers.dart';

/// Holds the elevator data for the maintenance operation flow.
/// Fetched when user scans QR code and needs to start maintenance.
final maintenanceOperationElevatorProvider =
    FutureProvider.family<ElevatorModel, String>((ref, elevatorId) async {
  final repo = ref.watch(elevatorRepositoryProvider);
  return repo.getElevatorById(elevatorId);
});

/// Manages the maintenance operation form state and submission.
class MaintenanceOperationController extends AutoDisposeAsyncNotifier<MaintenanceLogModel?> {
  @override
  Future<MaintenanceLogModel?> build() async => null;

  /// Submits a maintenance log with photos, signatures, and other data.
  /// 
  /// If offline, the operation is queued in Hive for later sync.
  /// If online, the operation is sent directly to Supabase.
  Future<void> submitMaintenanceLog({
    required String elevatorId,
    required String technicianId,
    required String findings,
    required List<String> photoUrls,
    required String? technicianSignatureUrl,
    required String? customerSignatureUrl,
    required String? pdfUrl,
    required DateTime maintenanceDate,
    required Map<String, bool> checklistItems,
    String? scheduleId,
  }) async {
    state = const AsyncLoading();

    final isOnline = ref.read(isOnlineProvider);

    final payload = <String, dynamic>{
      'elevator_id': elevatorId,
      'technician_id': technicianId,
      'notes': findings,
      'photos': photoUrls,
      'signature_url': technicianSignatureUrl,
      'customer_signature_url': customerSignatureUrl,
      'pdf_url': pdfUrl,
      'maintenance_date': maintenanceDate.toUtc().toIso8601String(),
      'checklist': checklistItems,
      'is_approved': false,
      if (scheduleId != null) '_schedule_id': scheduleId,
    };

    try {
      if (!isOnline) {
        // ── Offline: queue for later sync ────────────────────────────────
        final localMediaPaths = <String>[];
        final mediaFields = <String>[];

        if (photoUrls.isNotEmpty) {
          localMediaPaths.addAll(photoUrls);
          mediaFields.addAll(List<String>.filled(photoUrls.length, 'photos'));
        }

        if (technicianSignatureUrl != null &&
            technicianSignatureUrl.trim().isNotEmpty) {
          localMediaPaths.add(technicianSignatureUrl);
          mediaFields.add('signature_url');
        }

        if (customerSignatureUrl != null &&
            customerSignatureUrl.trim().isNotEmpty) {
          localMediaPaths.add(customerSignatureUrl);
          mediaFields.add('customer_signature_url');
        }

        if (pdfUrl != null && pdfUrl.trim().isNotEmpty) {
          localMediaPaths.add(pdfUrl);
          mediaFields.add('pdf_url');
        }

        if (mediaFields.isNotEmpty) {
          payload['_media_fields'] = mediaFields;
          payload['_media_list_fields'] = const ['photos'];
        }

        await ref.read(syncQueueServiceProvider).enqueue(
          endpoint: SyncEndpoint.insertMaintenanceLog,
          payload: payload,
          localMediaPaths: localMediaPaths,
        );

        // Return a local representation so the UI knows it was queued
        state = AsyncData(
          MaintenanceLogModel(
            id: 'offline_${DateTime.now().millisecondsSinceEpoch}',
            elevatorId: elevatorId,
            technicianId: technicianId,
            notes: findings,
            photos: photoUrls,
            signatureUrl: technicianSignatureUrl,
            customerSignatureUrl: customerSignatureUrl,
            pdfUrl: pdfUrl,
            maintenanceDate: maintenanceDate,
            isApproved: false,
            isOfflineQueued: true,
          ),
        );
      } else {
        // ── Online: submit directly ──────────────────────────────────────
        final repo = ref.read(maintenanceRepositoryProvider);
        
        // Create the log entry and store in repository
        await repo.addLog(
          elevatorId: elevatorId,
          technicianId: technicianId,
          notes: findings,
          maintenanceDate: maintenanceDate,
        );
        
        // Build response model for UI feedback
        final log = MaintenanceLogModel(
          id: '', // Will be generated by Supabase
          elevatorId: elevatorId,
          technicianId: technicianId,
          notes: findings,
          photos: photoUrls,
          signatureUrl: technicianSignatureUrl,
          customerSignatureUrl: customerSignatureUrl,
          pdfUrl: pdfUrl,
          maintenanceDate: maintenanceDate,
          isApproved: false,
        );

        state = AsyncData(log);
      }
    } catch (e, stack) {
      state = AsyncError(e, stack);
    }
  }
}

/// Provider for the maintenance operation controller.
final maintenanceOperationControllerProvider =
    AutoDisposeAsyncNotifierProvider<MaintenanceOperationController, MaintenanceLogModel?>(
  MaintenanceOperationController.new,
);
