// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOy1JNS148QgB--mVOg7n2n-AbQUWdwrM',
    appId: '1:203437631230:android:403f6ce3a7ef607d7467af',
    messagingSenderId: '203437631230',
    projectId: 'asansor-efaed',
    storageBucket: 'asansor-efaed.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSBAEfgIjZ-LrDKfKRiLjmFiNFo-oFSNk',
    appId: '1:203437631230:ios:d0d628fe24cacabc7467af',
    messagingSenderId: '203437631230',
    projectId: 'asansor-efaed',
    storageBucket: 'asansor-efaed.firebasestorage.app',
    iosBundleId: 'com.asansor.asansor',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBwYXH-h3UIUcgR8ACMxsRiqVISnWQjiA4',
    appId: '1:203437631230:web:b5b26a5fc6b228537467af',
    messagingSenderId: '203437631230',
    projectId: 'asansor-efaed',
    authDomain: 'asansor-efaed.firebaseapp.com',
    storageBucket: 'asansor-efaed.firebasestorage.app',
    measurementId: 'G-1DTJ7P49W7',
  );

}