import 'package:supabase_flutter/supabase_flutter.dart';

import '../models/elevator_model.dart';

class ElevatorRepository {
  ElevatorRepository(this._client);

  final SupabaseClient _client;

  static const _table = 'elevators';

  /// Returns every elevator record ordered by building name.
  Future<List<ElevatorModel>> getAllElevators() async {
    try {
      final response = await _client
          .from(_table)
          .select()
          .order('building_name', ascending: true);

      return (response as List<dynamic>)
          .map((json) => ElevatorModel.fromJson(json as Map<String, dynamic>))
          .toList();
    } on PostgrestException catch (e) {
      throw Exception('Failed to load elevators: ${e.message}');
    } catch (e) {
      throw Exception('Unexpected error while loading elevators: $e');
    }
  }

  /// Creates a new elevator record and returns the saved [ElevatorModel].
  ///
  /// The `id` (UUID) is generated by Supabase on insert.
  /// [maintenanceDay] is the contract day of the month (1–28) for periodic
  /// maintenance.  Pass null if no contract has been configured.
  Future<ElevatorModel> createElevator({
    required String buildingName,
    String? address,
    String status = 'active',
    double? latitude,
    double? longitude,
    int? maintenanceDay,
  }) async {
    try {
      final optionalFields = <String, dynamic>{
        'latitude': latitude,
        'longitude': longitude,
        'maintenance_day': maintenanceDay,
      }..removeWhere((_, value) => value == null);

      final response = await _client
          .from(_table)
          .insert({
            'building_name': buildingName,
            'address': address?.isNotEmpty == true ? address : null,
            'status': status,
            ...optionalFields,
          })
          .select()
          .single();

      return ElevatorModel.fromJson(response);
    } on PostgrestException catch (e) {
      throw Exception('Asansör oluşturulamadı: ${e.message}');
    } catch (e) {
      throw Exception('Beklenmeyen hata: $e');
    }
  }

  /// Returns a single elevator by its [id].
  Future<ElevatorModel> getElevatorById(String id) async {
    try {
      final response = await _client
          .from(_table)
          .select()
          .eq('id', id)
          .single();

      return ElevatorModel.fromJson(response);
    } on PostgrestException catch (e) {
      throw Exception('Failed to load elevator ($id): ${e.message}');
    } catch (e) {
      throw Exception('Unexpected error while loading elevator ($id): $e');
    }
  }
}
