import 'package:supabase_flutter/supabase_flutter.dart';

import 'package:asansor/core/exceptions/app_exception.dart';
import 'package:asansor/features/elevator/models/elevator_model.dart';

abstract interface class IElevatorRepository {
  Future<List<ElevatorModel>> getAllElevators({
    int limit = 100,
    int offset = 0,
  });
  Future<ElevatorModel> createElevator({
    required String buildingName,
    String? address,
    String status = 'active',
    double? latitude,
    double? longitude,
    int? maintenanceDay,
  });
  Future<ElevatorModel> getElevatorById(String id);
}

class ElevatorRepository implements IElevatorRepository {
  ElevatorRepository(this._client);

  final SupabaseClient _client;

  static const _table = 'elevators';

  /// Returns every elevator record ordered by building name.
  @override
  Future<List<ElevatorModel>> getAllElevators({
    int limit = 100,
    int offset = 0,
  }) async {
    try {
      final response = await _client
          .from(_table)
          .select()
          .order('building_name', ascending: true)
          .range(offset, offset + limit - 1);

      return (response as List<dynamic>)
          .map((json) => ElevatorModel.fromJson(json as Map<String, dynamic>))
          .toList();
    } on AppException {
      rethrow;
    } on PostgrestException catch (e) {
      throw mapPostgrestException(e, 'getAllElevators');
    } catch (e) {
      throw mapUnknownException(e, 'getAllElevators');
    }
  }

  /// Creates a new elevator record and returns the saved [ElevatorModel].
  ///
  /// The `id` (UUID) is generated by Supabase on insert.
  /// [maintenanceDay] is the contract day of the month (1–28) for periodic
  /// maintenance.  Pass null if no contract has been configured.
  @override
  Future<ElevatorModel> createElevator({
    required String buildingName,
    String? address,
    String status = 'active',
    double? latitude,
    double? longitude,
    int? maintenanceDay,
  }) async {
    try {
      final optionalFields = <String, dynamic>{
        'latitude': latitude,
        'longitude': longitude,
        'maintenance_day': maintenanceDay,
      }..removeWhere((_, value) => value == null);

      final response = await _client
          .from(_table)
          .insert({
            'building_name': buildingName,
            'address': address?.isNotEmpty == true ? address : null,
            'status': status,
            ...optionalFields,
          })
          .select()
          .single();

      return ElevatorModel.fromJson(response);
    } on AppException {
      rethrow;
    } on PostgrestException catch (e) {
      throw mapPostgrestException(e, 'createElevator');
    } catch (e) {
      throw mapUnknownException(e, 'createElevator');
    }
  }

  /// Returns a single elevator by its [id].
  @override
  Future<ElevatorModel> getElevatorById(String id) async {
    try {
      final response = await _client
          .from(_table)
          .select()
          .eq('id', id)
          .single();

      return ElevatorModel.fromJson(response);
    } on AppException {
      rethrow;
    } on PostgrestException catch (e) {
      throw mapPostgrestException(e, 'getElevatorById($id)');
    } catch (e) {
      throw mapUnknownException(e, 'getElevatorById($id)');
    }
  }
}
