-- =============================================================================
-- Migration: Periodic Contract & Auto-Scheduling support
-- =============================================================================
-- Run this once against your Supabase project.
--
-- How to apply
-- ─────────────────────────────────────────────────────────────────────────────
--   Option A — Supabase Dashboard SQL Editor: paste and execute.
--   Option B — CLI (recommended):
--     supabase db push
--     (file must be in supabase/migrations/ with a timestamp prefix, e.g.
--      20241201000000_add_maintenance_day_and_task_type.sql)
-- =============================================================================

-- ── 1. elevators: add contract maintenance day ────────────────────────────────
--
-- maintenance_day stores the calendar day (1–28) on which the service
-- contract mandates a periodic maintenance visit.  Capped at 28 so the date
-- is always valid in every calendar month including February.
-- NULL means no periodic maintenance contract has been configured yet.

ALTER TABLE elevators
  ADD COLUMN IF NOT EXISTS maintenance_day INTEGER
  CHECK (maintenance_day BETWEEN 1 AND 28);

-- ── 2. maintenance_schedules: allow unassigned technician ─────────────────────
--
-- Auto-generated periodic tasks are created without a specific technician so
-- the admin can assign them later from the unassigned pool.
-- The NOT NULL constraint is therefore relaxed.

ALTER TABLE maintenance_schedules
  ALTER COLUMN technician_id DROP NOT NULL;

-- ── 3. maintenance_schedules: add task_type discriminator ─────────────────────
--
-- task_type distinguishes auto-generated periodic tasks from manually assigned
-- ones.  Existing rows default to 'manual'.
--
-- Values:
--   'manual'               – created by an admin via the Assign form
--   'periodic_maintenance' – auto-generated by AutoScheduleService

ALTER TABLE maintenance_schedules
  ADD COLUMN IF NOT EXISTS task_type TEXT NOT NULL DEFAULT 'manual';

-- ── 4. Verification queries (run optionally to confirm) ───────────────────────
--
-- SELECT column_name, data_type, is_nullable, column_default
-- FROM information_schema.columns
-- WHERE table_name IN ('elevators', 'maintenance_schedules')
--   AND column_name IN ('maintenance_day', 'technician_id', 'task_type')
-- ORDER BY table_name, column_name;
